import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/main.ts',
    'src/shell.ts',
    'src/shell-wallet.ts',
    'src/wallet-identity.ts',
    'src/share-target.ts',
    'src/dapps/about/dapp.ts',
    'src/dapps/projects/dapp.ts',
    'src/dapps/support/dapp.ts',
    'src/dapps/tpl/dapp.ts',
    'src/dapps/cic/dapp.ts',
    'src/dapps/cic/cic.ts',
    'src/plugins/ethereum.ts',
    'src/dapps/settings/dapp.ts',
    'src/dapps/settings/settings.ts',
    'src/dapps/settings/fields.ts',
    'src/dapps/settings/sync.ts',
    'src/dapps/decode/codecs.ts',
    'src/dapps/decode/keccak.ts',
    'src/dapps/decode/abi.ts',
    'src/dapps/decode/core.ts',
    'src/dapps/decode/transport.ts',
    'src/dapps/decode/signatures.ts',
    'src/dapps/decode/decoders.ts',
    'src/dapps/decode/decoders-jwt.ts',
    'src/dapps/decode/decoders-eth-calldata.ts',
    'src/dapps/decode/decoders-abi-words.ts',
    'src/dapps/decode/decoders-url.ts',
    'src/dapps/decode/decoders-base64.ts',
    'src/dapps/decode/ui.ts',
    'src/dapps/decode/dapp.ts',
  ],
  // Transpile only — no bundling, no wrapping
  bundle: false,
  format: ['esm'],
  outDir: 'src',
  splitting: false,
  clean: false,
  platform: 'browser',
  target: 'es2022',
  // Output .js alongside .ts sources
  outExtension: () => ({ js: '.js' }),
});
